# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e247c7bbfd924730f1f9244ca0cfa3f41d6b051e747c0643539228aa5243bd28d444e0c74aa4d991d37e42c42882f22362068e83aea1e8ca645096d6e3de5f3

test:
  secret_key_base: a6ddec493a04539dba85c0635ff6951e0a0c72b1147310c618b13ff4e4c8409616395895f55038c5bc850ce5ab0ecaf5f2a4175b5ff5327a1b3bdfad72479c73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
